### PR TITLE
Add saving and loading to JSON

### PR DESCRIPTION
**Pull request by crhallberg**
Initial draft. Tried to make it compact. Would love feedback!

- [x]  Should toJSON export an object or a string?

UPDATE:
File size is an issue. I transformed a 98MB CSV into a QuadTree and the JSON output is 144MB. I know JSON is fairly verbose, perhaps there's another way to encode this.

### CODE REVIEW

**Comment by crhallberg** [comment]
I did some benchmarking to see if this was worth it. [Code available in this gist](https://gist.github.com/crhallberg/da8716bd44031bf8812f48bf49d3b2e6).

image

Parsing the JSON takes about 200ms if it seems fairer to include that in the time.

**Comment by crhallberg** [comment]
After reviewing a few libraries, most toJSON methods return objects. Plus, fromJSON was expecting an object.

**Comment by shiffman** [comment]
@crhallberg Hi! Thank you for all of this work! I haven't been able to keep up with this repo, but I am planning to use it next week in my "Nature of Code" class at ITP in combination with the flocking example. Would you be interested in having write permissions to this repo and managing the various pull requests and issues?

**Comment by shiffman** [comment]
I went through a bunch of the pull requests and have gotten more of a handle on the library! I'm happy to include this if you want to fix the merge conflicts!

**Comment by crhallberg** [comment]
1/ Thank you for the invite! I could definitely help facilitate this repository if you added me. I think this tool is a great and easy to use QuadTree and a great teaching tool as part of Coding Train. Thank you!

2/ I'll fix the merge errors soon! If you don't want to merge this before your class to avoid surprises, that makes sense too!

**Pull request merged**
