### PR TITLE
Slight changes all over the place + flocking example

### PR DESCRIPTION
**Pull request by mike239x**
The names of commits say it, pretty much. Biggest change is the magic for circle/rect intersection. 

P.S. I must say that I didn't run any tests (`npm run test` throws no errors but opens some kind of IDLE of `nyc`, didn't investigate), but the code works fine.

### CODE REVIEW

**Comment by mike239x** [comment]
Oh yeah, I am also getting this in the console: 
"ReferenceError: module is not defined" 
regarding the last line in `quadtree.js`:
`((module ? module.exports = { Point, Rectangle, QuadTree, Circle } : 0));`
I do hope this is an error only I have.

**Comment by Dezzles** [comment]
Tested your changes on my PC, all tests seem to be passing, not sure what why `npm run test` isn't working properly for you.
module error should be fine and I'll look into how to remove that error in the future, it's not you're fault it's mine

**Comment by mike239x** [comment]
That flocking thing I got right now looks so funny that I almost want to leave everything as it is :D

**Comment by mike239x** [comment]
Now it is working, though I still didn't figure out how to put slider right next to its label.
Also, added [GitHub Page](https://mike239x.github.io/QuadTree/examples/flocking/).

**Comment by WakeMeAtThree** [comment]
This is beautiful!

**Pull request closed without merging**
